config/routes.rb
Rails.application.routes.draw do
  resources :countries
  namespace :countries do
    resource :imports, only: [:new, :create]
  end
  root to: 'welcome#index'
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  has_one_attached :flag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries/imports_controller.rb
class Countries::ImportsController < ApplicationController
  def new
  end

  def create
    file = params[:file]

    blob = ActiveStorage::Blob.create_and_upload!(
      io: file,
      filename: file.original_filename,
      content_type: file.content_type
    )
    Countries::ImportJob.perform_later(blob.signed_id)
    redirect_to countries_path, notice: "Countries are being imported..."
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries
  def index
    @countries = Country.all
  end

  # GET /countries/1
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to @country, notice: "Country was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /countries/1
  def update
    if @country.update(country_params)
      redirect_to @country, notice: "Country was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /countries/1
  def destroy
    @country.destroy!
    redirect_to countries_url, notice: "Country was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name, :flag)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

  <p>
    <strong>Flag:</strong>
    <%= link_to country.flag.filename, country.flag if country.flag.attached? %>
  </p>

</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :flag, class: 'form-label' %>
    <%= form.file_field :flag, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/imports/new.html.erb
<%= form_with url: countries_imports_path do |f| %>
  <div class="mb-3">
    <%= f.label :file, class: "form-label" %>
    <%= f.file_field :file, class: "form-control" %>
  </div>

  <%= f.submit "Import", class: "btn btn-primary" %>
<% end %>

app/views/countries/index.html.erb
<h1>Country</h1>

<table class='table'>
  <thead>
    <th>Name</th>
    <th>Flag</th>

    <th colspan=3>Actions</th>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td>
          <%= image_tag country.flag.variant(resize_to_limit: [30, 30]) if country.flag.attached? && country.flag.image? %>
        </td>

        <td><%= link_to "Show", country_path(country) %></td>
        <td><%= link_to "Edit", edit_country_path(country) %></td>
        <td>
          <%= link_to "Delete", country_path(country),
            "data-turbo-method": :delete,
            "data-turbo-confirm": "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New country", new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<%= render @country %>

<div>
  <%= link_to "Edit", edit_country_path(@country) %> |
  <%= link_to "Destroy", country_path(@country),
    "data-turbo-method": :delete,
    "data-turbo-confirm": "Are you sure?" %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" data-config-id="brand">
      <%= image_tag 'logo.png', class: 'img-fluid' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="d-none d-lg-flex navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav-item me-4">
  <%= link_to "Home", root_path, class: 'nav-link' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class='bg-light'>
    <div class="container bg-white border pb-3">
      <%= render 'layouts/navigation' %>
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <%= content_tag :div, msg, class: "alert alert-danger", role: :alert %>
          <% else %>
          <%= content_tag :div, msg, class: "alert alert-primary", role: :alert %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Import Countries", new_countries_imports_path %>